# Generated by Django 4.2.2 on 2023-06-19 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0004_userdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='psw',
            field=models.CharField(default='21@sax', max_length=20),
        ),
    ]
